### ISSUE TITLE
Project Proposal Feedback

### ISSUE THREAD

**Issue by PhilChodrow** [asmit-a/pic-16b-project#1]
Hi Eva and Asmita, 

This looks like a fascinating project! I'm excited to see what you produce. 

Your proposal meets specifications, but there's one specific thing on which I'd like you to change your approach. When working with U.S. Census data, the best thing to do is usually not to *scrape* the data but rather to *access* it using one of the many Census Application Programming Interfaces (APIs). These APIs allow you to programmatically request Census data in a way that is both easier and more polite than scraping. There are multiple ways to use the APIs. One good one appears to be [this Python package](https://github.com/datamade/census), which will allow you to construct queries using Python code. 

Additionally, I find [this tool](https://censusreporter.org) very helpful when trying to find tables of data corresponding to a specific subject. 

To complete your proposal, I'd like you to make revisions specifying that you will be using API access rather than scraping. I'd also like you to spend a bit of time examining the options for working with APIs (I've suggested one, but there are others). You should pick one that you're going to use (or, at least, try first), and state how you made that choice. Once you've done that, reply to this issue. I'll read your revised proposal and assess credit. 

I'm excited to see what you create!

**Comment by asmit-a** [comment]
Hi Professor, 

Sorry for the delay! We've revised our proposal. Thanks for all of your help!

**Comment by asmit-a** [comment]
> Hi Eva and Asmita,
> 
> This looks like a fascinating project! I'm excited to see what you produce.
> 
> Your proposal meets specifications, but there's one specific thing on which I'd like you to change your approach. When working with U.S. Census data, the best thing to do is usually not to _scrape_ the data but rather to _access_ it using one of the many Census Application Programming Interfaces (APIs). These APIs allow you to programmatically request Census data in a way that is both easier and more polite than scraping. There are multiple ways to use the APIs. One good one appears to be [this Python package](https://github.com/datamade/census), which will allow you to construct queries using Python code.
> 
> Additionally, I find [this tool](https://censusreporter.org) very helpful when trying to find tables of data corresponding to a specific subject.
> 
> To complete your proposal, I'd like you to make revisions specifying that you will be using API access rather than scraping. I'd also like you to spend a bit of time examining the options for working with APIs (I've suggested one, but there are others). You should pick one that you're going to use (or, at least, try first), and state how you made that choice. Once you've done that, reply to this issue. I'll read your revised proposal and assess credit.
> 
> I'm excited to see what you create!

Hi Professor,

Sorry for the delay! We've revised our proposal. Thanks for all of your help!

**Comment by PhilChodrow** [comment]
Looks great, nice work! You have received credit for your proposal.
